// eslint.config.mjs
import { defineConfig, globalIgnores } from 'eslint/config'
import nextConfig from 'eslint-config-next/core-web-vitals'

export default defineConfig([
  ...nextConfig,
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    // Generated by `npm run test:coverage` — vendored reporter assets, not ours.
    'coverage/**',
    'next-env.d.ts'
  ]),
])
